# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

<http://purl.org/NET/cpan-uri/dist/HTML-HTML5-Parser/project>
	:runtime-requirement    [ :on "perl 5.008001"^^:CpanId ];
	:runtime-requirement    [ :on "Try::Tiny"^^:CpanId ];
	:runtime-requirement    [ :on "IO::HTML"^^:CpanId ];
	:runtime-requirement    [ :on "HTML::HTML5::Entities 0.002"^^:CpanId ];
	:runtime-requirement    [ :on "HTTP::Tiny"^^:CpanId ];
	:runtime-requirement    [ :on "XML::LibXML 1.94"^^:CpanId ];
	:runtime-requirement    [ :on "XML::LibXML::Devel"^^:CpanId ];
	:runtime-requirement    [ :on "Scalar::Util"^^:CpanId ];
	:runtime-requirement    [ :on "URI::file"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.61"^^:CpanId ];
	:test-requirement       [ :on "Test::Requires"^^:CpanId ];
	:test-requirement       [ :on "FindBin"^^:CpanId ];
	:test-recommendation    [ :on "LWP::UserAgent"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.
