# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/HTML-HTML5-Parser/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires "Test::More 0.61" ;
	:requires "Error" ;
	:requires "HTML::Encoding 0.55" ;
	:requires "HTML::HTML5::Entities 0.001" ;
	:requires "LWP::UserAgent" ;
	:requires "XML::LibXML 1.60" ;
	:requires "Scalar::Util" ;
	:install_script _:html5debug , _:html2xhtml .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/HTML/HTML5/Parser.pm" .
_:html5debug <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "bin/html5debug" .
_:html2xhtml <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "bin/html2xhtml" .
